executor: slurm
software-deployment-method: conda
keep-going: true
rerun-incomplete: true
printshellcmds: true
scheduler: greedy
max-jobs-per-second: 1
max-status-checks-per-second: 1
local-cores: 2
latency-wait: 60
jobs: 5000
cores: all

resources:
  gdc_download_jobs: 24

default-resources:
  slurm_partition: "ccr,norm"
  cpus_per_task: 4
  mem: "8g"
  runtime: "10d"
  slurm_extra: "'--gres=lscratch:100'"

set-resources:
  host_genome_index:
    cpus_per_task: 28
    mem: "32g"

  host_filtered_fastq_pe:
    cpus_per_task: 4
    mem: "16g"

  host_filtered_fastq_se:
    cpus_per_task: 4
    mem: "16g"

  kraken2_nucl_db_library:
    cpus_per_task: 12
    mem: "8g"

  kraken2_prot_db_library:
    cpus_per_task: 12
    mem: "8g"

  kraken2_db:
    cpus_per_task: 56
    mem: "64g"

  kraken2_nucl_read_classif_pe:
    cpus_per_task: 8
    mem: "64g"

  kraken2_nucl_read_classif_se:
    cpus_per_task: 8
    mem: "64g"

  kraken2_prot_read_classif_pe:
    cpus_per_task: 8
    mem: "64g"

  kraken2_prot_read_classif_se:
    cpus_per_task: 8
    mem: "64g"

  krakenuniq_db_taxonomy:
    cpus_per_task: 12
    mem: "8g"

  krakenuniq_db_library:
    cpus_per_task: 12
    mem: "8g"

  krakenuniq_db:
    cpus_per_task: 56
    mem: "64g"

  krakenuniq_read_classif_pe:
    cpus_per_task: 8
    mem: "64g"

  krakenuniq_read_classif_se:
    cpus_per_task: 8
    mem: "64g"

  bracken_db:
    cpus_per_task: 56
    mem: "64g"
